# Generated by Django 5.2.6 on 2025-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Average'), (2, 'Good'), (3, 'Very Good')]),
        ),
    ]
